# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 'development'
  pull_request:
    branches: 'development'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
          
        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x
            
        - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            
        - name: Install dependencies
          run: yarn install 
          
        - name: Generate build
          run: yarn run build
          
        # Share artifact inside workflow
        - name: Share artifact inside workflow
          uses: actions/upload-artifact@v2
          with:
            name: scart_web_${{ github.sha }}
            path: build

             
